# Generated by Django 4.2.9 on 2024-07-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
