# Generated by Django 4.2.9 on 2024-07-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_states'),
    ]

    operations = [
        migrations.RenameField(
            model_name='states',
            old_name='states',
            new_name='state_name',
        ),
    ]
