# Generated by Django 4.2.9 on 2024-07-18 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_states_states_state_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=250)),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.states')),
            ],
        ),
    ]
