# Generated by Django 4.2.9 on 2024-07-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_questions_if_view_alter_choices_is_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='if_view',
        ),
        migrations.AlterField(
            model_name='choices',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
    ]
