# Generated by Django 4.2.9 on 2024-07-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_questions_if_view_alter_choices_is_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='if_view',
            field=models.BooleanField(default=True),
        ),
    ]
