# Generated by Django 4.2.9 on 2024-07-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_questions_if_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='backgrounds/')),
                ('type', models.CharField(max_length=500)),
            ],
        ),
    ]
