# Generated by Django 4.2.9 on 2024-08-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_user_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='medium',
            field=models.CharField(default='English', max_length=100),
            preserve_default=False,
        ),
    ]
